### ISSUE TITLE
Warnings for unused type variables.

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#132]
In Julia 1.8.2 we now get a few warnings for unused types in the fallbacks, for example

```
WARNING: method definition for allocate at ManifoldsBase.jl/src/point_vector_fallbacks.jl:27 declares type variable _ but does not use it.
WARNING: method definition for allocate at ManifoldsBase.jl/src/point_vector_fallbacks.jl:28 declares type variable _ but does not use it.
```

wich is a little hard to read since it is in a macro, but I think we have to adapt the `$Twhere` to be meow flexible? Maybe a point and a vector type specifically?

**Comment by mateuszbaran** [comment]
Good point, I haven't updated to 1.8.2 before so I didn't notice them. I will fix them during this weekend.
