### ISSUE TITLE
Change function signature of `is_` functions to be consistent with `isapprox`.

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#135]
To be consistent with the newly planned error mode, these two positional arguments of `is_point` (for the first) and `is_vector` these two should become keyword arguments.
This should also be done for the internal `check_` functions also for consistency with the `isapprox` and `check_approx` functions,
see also discussions in #134.

**Comment by kellertuer** [comment]
...somehow we did not do this in 0.14.0 ;)

**Comment by mateuszbaran** [comment]
I forgot to check :/.
