### ISSUE TITLE
Were we not careful enough with ManifoldsBase 0.14?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#147]
I just noticed that since ManifoldsBase 0.14 we have quite a few inexact errors with NaNs?

see

https://github.com/JuliaManifolds/ManifoldsBase.jl/actions/runs/4187041219/jobs/7256354396#step:5:354

**Comment by kellertuer** [comment]
...or are those expected infos? Then I would switch them to test_logs in my next PR.

**Comment by mateuszbaran** [comment]
I've added those tests on purpose, maybe it should be done a bit differently -- I didn't know about test_logs.

**Comment by kellertuer** [comment]
Already fixed it in the linked new PR :) 

I feel if there is info-things printed it should be for a reason and Error-Infos might be misleading (for example for me sometimes) so now they are in log-checks :)
