### ISSUE TITLE
`get_vectors`not working on a (nested) Power manifold of a product manifold.

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#199]
Consider

```
using Manifolds
S = Sphere(2) × ℝ^1
N = PowerManifold(S, NestedPowerRepresentation(), 2)
q = rand(N)
C = get_basis(N, q, DefaultOrthonormalBasis())
get_vectors(N, q, C)
```

This throws an error

```
ERROR: MethodError: no method matching iterate(::ProductBasisData{Tuple{CachedBasis{ℝ, DefaultOrthonormalBasis{…}, Vector{…}}, CachedBasis{ℝ, DefaultOrthonormalBasis{…}, Vector{…}}}})

Closest candidates are:
  iterate(::Core.Compiler.InstructionStream, ::Int64)
   @ Base show.jl:2778
  iterate(::Core.Compiler.InstructionStream)
   @ Base show.jl:2778
  iterate(::LazyString)
   @ Base strings/lazy.jl:94
  ...

Stacktrace:
 [1] _get_vectors(M::PowerManifold{ℝ, ProductManifold{…}, Tuple{…}, NestedPowerRepresentation}, p::Vector{ArrayPartition{…}}, B::CachedBasis{ℝ, DefaultOrthonormalBasis{…}, PowerBasisData{…}})
   @ ManifoldsBase ~/Repositories/Julia/ManifoldsBase.jl/src/PowerManifold.jl:828
 [2] get_vectors(M::PowerManifold{ℝ, ProductManifold{…}, Tuple{…}, NestedPowerRepresentation}, p::Vector{ArrayPartition{…}}, B::CachedBasis{ℝ, DefaultOrthonormalBasis{…}, PowerBasisData{…}})
   @ ManifoldsBase ~/Repositories/Julia/ManifoldsBase.jl/src/bases.jl:821
 [3] top-level scope
   @ REPL[7]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

So in line https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/1bf814993c3b7bfd1d5667dca9457c010541a102/src/PowerManifold.jl#L827

it seems that the ProdyctBasisData is not iterable. I could fix that with writing instead of 

```
        for v in b_i.data
```

just

```
        for v in get_vectors(M.manifold, p_i, b_i)
```

but that materialises all vectors here. So what is the right fix for this?

**Comment by mateuszbaran** [comment]
My quick guess is than `for v in get_vectors(M.manifold, p_i, b_i)` is fine in this case. Anyway, if you are doing `get_vectors` on a power manifold, you're doing something extremely sub-optimally anyway.

**Comment by mateuszbaran** [comment]
If `for v in get_vectors(M.manifold, p_i, b_i)` works fine then I'm fine with that fix in ManifoldsBase :slightly_smiling_face:

**Comment by kellertuer** [comment]
Ok, I was just not sure about performance, but maybe if one wants all vectors on a power manifold, performance is nothing to worry about any longer anyways (we only needed about 200 vectors or such)

**Comment by mateuszbaran** [comment]
For debugging it should be fast enough. In the main computations it shouldn't be used so it being slow doesn't matter.

**Comment by kellertuer** [comment]
Ok, sure. Then I will do a PR soon with that fix.
