### ISSUE TITLE
Parametrize Manifold by its eltype/number system

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#30]
I would like to add a parameter to `Manifold`, i.e. its number_system. This would

* unify `Manifold` with `Bases`
* make a general implelemtation of ` numbersystem(M::Manifold{F}) = F` possible
* simplify subaccordingy a few implementations here and for Manifolds later on

What do you think?

**Comment by mateuszbaran** [comment]
One reason why it'd be problematic is the product manifold. I'm already not quite sure how well product bases will handle bases of mixed real-complex manifolds. `ProductManifold` implements a lot of basis-related functionality that should make this work but maybe we should have a "Mixed number system" or something to indicate that no default fallback that relies on the number system will work?

**Comment by kellertuer** [comment]
The `ProductManifold` should take the parent type (i.e. complex as soon as a complex manifold is involved) for example, but also “keep track” of its children's types and dispatch thereon correctly. 
For the elements of product it should still work fine. But basically we already have the same problem then for any basis of a `ProductManifold`? The basis is already parametrized by its number system.

Another possibility would of course be to forbid mixed manifold and say: If you take a complex one, please make them all complex. I think I'd prefere the first, mixed one.

**Comment by mateuszbaran** [comment]
Yes, bases have the same problem and there it currently works by having to explicitly give the number system, and the number system is not reverted to real numbers for real manifolds. Product manifolds however store the component manifolds and parametrizing manifolds by number system would fix this problem.

I wouldn't like to restrict product manifolds to the have the same number system.

So, with that in mind, I think adding the number system to manifolds is a good idea 🙂 .

**Comment by kellertuer** [comment]
I think that is a good restriction. So we should add the number system as a parameter to manifolds then.

**Comment by mateuszbaran** [comment]
Resolved by #32
