### ISSUE TITLE
Should representation_size return nothing by default?

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/ManifoldsBase.jl#34]
As in the title, I think this would allow for better support of manifolds that don't have `representation_size`.

**Comment by kellertuer** [comment]
What would be the use case/reason?

**Comment by mateuszbaran** [comment]
Most methods of `PowerManifold` call `representation_size` but the nested variant can work perfectly well with points on manifolds that don't have `representation_size`. Returning `nothing` by default would make adaptation of `PowerManifold` to support that case much easier.

**Comment by kellertuer** [comment]
Sounds good to me.

**Comment by kellertuer** [comment]
Have you had the time to check this? Currently I am having a problem where for `Circle()` and `Euclidean(1)` – so for `PowerManifolds` that basically do not have arrays, sizes are somethimes `(,)`or `(1,)`. This might help for that case.

**Comment by mateuszbaran** [comment]
Actually real circle should have size `(,)` and `Euclidean(1)` should have size `(,)`. What's the problem with that? This issue is just about a small cleanup of the interface.

**Comment by kellertuer** [comment]
Both are represented just by numbers or am I having that wrong and the equivalent (non-array) one is `Euclidean()`? Mainly I got stuck somewhere in debugging `differential_forward_logs` When working with `Circle()` (and its `PowerManifold`) and a tangent bundle of that power manifold. But I have to take a closer look there, then, before more precisely stating the problem I might still have.

**Comment by mateuszbaran** [comment]
Sorry for not responding earlier, I have missed this earlier. Yes, `Euclidean()` is the no-index Euclidean space where points are represented using zero-index arrays.
