### ISSUE TITLE
Remove non-implemented-errors?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#35]
I recently stumbled upon this article (in preparation): https://github.com/oxinabox/oxinabox.github.io/pull/14/files#diff-e18e780852d70bbdfc8ecbe3aca97a23R22 on anti patterns.

The author writes, that writing own error messages is not useful, so instead of doing ( https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/master/src/ManifoldsBase.jl#L369-L371 )

````julia
function exp!(M::Manifold, q, p, X)
    error(manifold_function_not_implemented_message(M, exp!, q, p, X))
end
````

we should just to

````julia
function exp! end
````

What I do not really like in this, is that you seem to not be able to provide arguments, so it is not so easy to document functions that we extend and that do not have default implementations (do we have such)?

The advantage is, that instead of `ErrorExceptions` `MethodErrors` are thrown, with the advantage, that the suggestions are provided in case you just missed a type. I even ran into this independently yesterday, so I wanted to discuss whether to do that.

The only point where I see a useful case for error messages is within the decorator dispatch.

What do you think?

**Comment by mateuszbaran** [comment]
> What I do not really like in this, is that you seem to not be able to provide arguments, so it is not so easy to document functions that we extend and that do not have default implementations (do we have such)?

`manifold_dimension` is probably the only important example.

I don't have strong feelings about it either way. We avoid the main problem with error messages by making them quite explicit about types of arguments but they indeed don't seem to provide much value.

> The only point where I see a useful case for error messages is within the decorator dispatch.

Yes, and in that case they even could be longer, referring the user to documentation about decorators for help about figuring out what went wrong.

**Comment by kellertuer** [comment]
I thought about this and indeed we might require the error messages due to our decorator dispatch.
