### ISSUE TITLE
Matrix multiplication in tangent spaces

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldsBase.jl#45]
I stumbled upon an interesting modelling question, when checking code (for example from https://www.math.fsu.edu/~whuang2/papers/ROPTLIB.htm or manopt.org), namely:

How to best define matrix multiplication or more generally linear operators on (or even between) tangent spaces.

The long way, of course, is `get_coordinates` and then a matrix multiplication in coordinates. Maybe this is even a good default. But can we phrase this more general/generic?
We might need a type for that. With the ideas
* evaluated at `p` on a manifold, one gets a linear operator
* this linear operator could be overloaded with a `*`

I was ´thinking of maybe even a functor, such hat for an instance `H` `H(p)` returns the linear operator at `p` that might still map into a tangent space at `q` but accepts as input elements from  TpM.

What are your ideas to such a construction?
I might also first try it in Manopt.jl before getting it into `ManifoldsBase`.

**Comment by mateuszbaran** [comment]
That's a great question, and also relevant to Jacobian calculation in https://github.com/JuliaManifolds/Manifolds.jl/pull/110 (I probably shouldn't call it Jacobian though). We could also discuss bilinear (or even multilinear) maps.

Maybe something like
```julia
abstract type MultilinearOperator end
abstract type MultilinearScalarValuedOperator end
abstract type MultilinearTangentValuedOperator end

function apply_operator(op::MultilinearOperator, x...) end
*(op::MultilinearOperator, x) = apply_operator(op, x)

function apply_operator!(op::MultilinearTangentValuedOperator, X, x...) end
```

> I was ´thinking of maybe even a functor, such hat for an instance `H` `H(p)` returns the linear operator at `p` that might still map into a tangent space at `q` but accepts as input elements from TpM.

What examples do you have in mind?

By the way, maybe representation of cotangent vectors is also a relevant issue here.

These are just some quick comments, I'll keep thinking about it.

**Comment by kellertuer** [comment]
I just discussed a little bit with my student and we noticed, it might sometimes even be preferable to define the action in an embedding, for example for `Stiefel` or `Grassmann`, when thinking e.g. of the Hessian.

That's also the example I had in mind. `H` like the matrix representation of the Hessian, but you're right also the Jacobian (or push forward) falls into this regime.

**Comment by mateuszbaran** [comment]
Yes, sure, we would be free to define operators in any space we wanted, either embedding or coefficients in a basis.

I think I've forgotten about one thing, we don't necessarily want to wrap arrays representing `p` in such operators.

**Comment by mateuszbaran** [comment]
I've prepared a second version of my proposal:
```julia
```

**Comment by kellertuer** [comment]
I think this can be done in coordinates easier, since one has to track them for approaches mentioned here anyways, one could just do matrix multiplication in coordinates.

**Comment by mateuszbaran** [comment]
Doing it in coordinates is one way but I think for many operators it may be preferable to be able to do it coordinate-free. Anyway, there doesn't seem to currently be much need to introduce a common layer or interface for such operators.

**Comment by kellertuer** [comment]
If so I would maybe start that in Manifolds then anyways?

**Comment by mateuszbaran** [comment]
What do you want to start in Manifolds?
